branches:
  only:
    - master

skip_tags: true

version: "{build}"

assembly_info:
  patch: false

platform:
  - Any CPU

configuration:
  - Release

before_build:
  - cmd: nuget restore

build:
  project: magic_company_name_magic.magic_product_name_magic.magic_application_name_magic.sln
  verbosity: minimal
